#!/usr/bin/env bash
# tg-tor-gate installer
# Usage: bash <(curl -fsSL https://raw.githubusercontent.com/ali934h/tg-tor-gate/main/install.sh)
set -euo pipefail

REPO_URL="https://github.com/ali934h/tg-tor-gate.git"
INSTALL_DIR="/root/tg-tor-gate"
TORRC="/etc/tor/torrc"
SERVICE_FILE="/etc/systemd/system/tg-tor-gate.service"
SOCKS_PORT=9050
CONTROL_PORT=9051

color() { printf "\033[%sm%s\033[0m\n" "$1" "$2"; }
info()  { color "1;34" "==> $1"; }
ok()    { color "1;32" "✓ $1"; }
err()   { color "1;31" "✗ $1"; }

if [[ $EUID -ne 0 ]]; then
  err "This installer must be run as root."
  exit 1
fi

info "Installing system packages (tor, python3, git)…"
apt-get update -qq
apt-get install -y -qq tor python3 python3-venv python3-pip git curl >/dev/null
ok "System packages installed"

# --- Prompt for configuration -------------------------------------------

echo
info "Configuration"
read -rp "Telegram bot token (from @BotFather): " BOT_TOKEN
while [[ -z "$BOT_TOKEN" ]]; do
  read -rp "Bot token cannot be empty. Telegram bot token: " BOT_TOKEN
done

read -rp "Allowed Telegram user IDs, comma-separated (ask @userinfobot for yours): " ALLOWED_USERS_RAW
while [[ -z "$ALLOWED_USERS_RAW" ]]; do
  read -rp "At least one user ID is required. Allowed Telegram user IDs: " ALLOWED_USERS_RAW
done
ALLOWED_USERS_PY="[$(echo "$ALLOWED_USERS_RAW" | tr -d ' ' | sed 's/,/, /g')]"

read -rp "Tor SOCKS5 port [$SOCKS_PORT]: " SOCKS_PORT_IN
SOCKS_PORT="${SOCKS_PORT_IN:-$SOCKS_PORT}"

read -rp "Tor ControlPort [$CONTROL_PORT]: " CONTROL_PORT_IN
CONTROL_PORT="${CONTROL_PORT_IN:-$CONTROL_PORT}"

read -rp "Default exit country at startup (ISO code, e.g. DE — leave empty for any): " DEFAULT_COUNTRY
DEFAULT_COUNTRY="$(echo "$DEFAULT_COUNTRY" | tr '[:lower:]' '[:upper:]')"

# --- Configure Tor's control port ----------------------------------------

info "Configuring Tor ControlPort…"
CONTROL_PASSWORD="$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))')"
HASHED_PASSWORD="$(tor --hash-password "$CONTROL_PASSWORD" 2>/dev/null | tail -n1)"

# Strip any previous tg-tor-gate block, then append a fresh one (idempotent re-installs)
if [[ -f "$TORRC" ]]; then
  sed -i '/# --- tg-tor-gate begin ---/,/# --- tg-tor-gate end ---/d' "$TORRC"
else
  touch "$TORRC"
fi

cat >> "$TORRC" <<EOF

# --- tg-tor-gate begin ---
SocksPort 127.0.0.1:${SOCKS_PORT}
ControlPort 127.0.0.1:${CONTROL_PORT}
HashedControlPassword ${HASHED_PASSWORD}
# --- tg-tor-gate end ---
EOF

systemctl enable tor >/dev/null 2>&1 || true
systemctl restart tor
sleep 2
ok "Tor configured — SOCKS5 on 127.0.0.1:${SOCKS_PORT}, ControlPort on 127.0.0.1:${CONTROL_PORT}"

# --- Clone / update the repo ----------------------------------------------

info "Fetching tg-tor-gate…"
if [[ -d "$INSTALL_DIR/.git" ]]; then
  git -C "$INSTALL_DIR" pull --quiet
else
  rm -rf "$INSTALL_DIR"
  git clone --quiet "$REPO_URL" "$INSTALL_DIR"
fi
ok "Code in place at $INSTALL_DIR"

# --- Python environment ----------------------------------------------------

info "Setting up Python virtual environment…"
python3 -m venv "$INSTALL_DIR/.venv"
"$INSTALL_DIR/.venv/bin/pip" install --quiet --upgrade pip
"$INSTALL_DIR/.venv/bin/pip" install --quiet -r "$INSTALL_DIR/requirements.txt"
ok "Dependencies installed"

# --- config.py ---------------------------------------------------------------

cat > "$INSTALL_DIR/config.py" <<EOF
# Generated by install.sh — do not commit.

BOT_TOKEN = "${BOT_TOKEN}"
ALLOWED_USERS = ${ALLOWED_USERS_PY}

TOR_CONTROL_HOST = "127.0.0.1"
TOR_CONTROL_PORT = ${CONTROL_PORT}
TOR_CONTROL_PASSWORD = "${CONTROL_PASSWORD}"
TOR_SOCKS_HOST = "127.0.0.1"
TOR_SOCKS_PORT = ${SOCKS_PORT}

DEFAULT_COUNTRY = "${DEFAULT_COUNTRY}"
NEWNYM_COOLDOWN_SEC = 10
CIRCUIT_BUILD_WAIT_SEC = 6

ONIONOO_URL = "https://onionoo.torproject.org/details"
LOCATIONS_CACHE_FILE = "locations_cache.json"
LOCATIONS_CACHE_TTL_HOURS = 6
LOCATIONS_PER_PAGE = 8
MIN_EXIT_RELAYS = 1

IP_CHECK_URL = "https://api.ipify.org?format=json"
IP_CHECK_TIMEOUT_SEC = 15
EOF
chmod 600 "$INSTALL_DIR/config.py"
ok "config.py written"

if [[ -n "$DEFAULT_COUNTRY" ]]; then
  info "Applying default exit country ${DEFAULT_COUNTRY}…"
  "$INSTALL_DIR/.venv/bin/python3" - <<PYEOF
import sys
sys.path.insert(0, "$INSTALL_DIR")
import tor_control
tor_control.set_exit_country("${DEFAULT_COUNTRY}")
PYEOF
fi

# --- systemd service ----------------------------------------------------

info "Installing systemd service…"
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=tg-tor-gate Telegram bot
After=network.target tor.service
Requires=tor.service

[Service]
Type=simple
WorkingDirectory=${INSTALL_DIR}
ExecStart=${INSTALL_DIR}/.venv/bin/python3 ${INSTALL_DIR}/bot.py
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable tg-tor-gate >/dev/null 2>&1
systemctl restart tg-tor-gate
sleep 2

if systemctl is-active --quiet tg-tor-gate; then
  ok "tg-tor-gate is running"
else
  err "tg-tor-gate failed to start — check: journalctl -u tg-tor-gate -e"
  exit 1
fi

echo
ok "Install complete."
echo "  SOCKS5 proxy:   127.0.0.1:${SOCKS_PORT}"
echo "  Telegram bot:   open a chat and send /start"
echo "  Logs:           journalctl -u tg-tor-gate -f"
